name: 1235 (bf0app)

on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'src/**'
    - '.github/workflows/**'

permissions:
  contents: read

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git python3 python3-pip
    - name: Install rommy
      run: | 
        git clone https://github.com/wtvemac/rommy.git
        pip install -r rommy/requirements.txt
    - name: Make AppROM
      run: ./build_zefie_rom.sh
    - name: Validate
      run: rm -rf rommy/
    - uses: actions/upload-artifact@master
      with:
        name: htv-1235
        path: |
          htv-1235.o
